-- Updated Customer Authentication Context
-- This is the SQL structure after running manual_customer_setup.sql

-- Updated customers table structure will be:
/*
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- Keep for existing data
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20),
    date_of_birth DATE,
    gender VARCHAR(10),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    password_hash VARCHAR(255) -- NEW COLUMN for customer passwords
);
*/

-- RLS Policies that will be active:
-- 1. "Allow public customer registration" - FOR INSERT TO PUBLIC
-- 2. "Allow public customer login" - FOR SELECT TO PUBLIC  
-- 3. "Allow customer profile updates" - FOR UPDATE TO PUBLIC

-- Test customers that will be created:
-- Email: test@nirchal.com, Password: password123
-- Email: john@example.com, Password: password456
-- Email: jane@example.com, Password: password789
