# Cloudflare Pages Build Configuration
# This file helps debug build issues

build_output_directory = "dist"
build_command = "npm run build"
node_version = "18"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "8"