-- About sections table
CREATE TABLE about_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    content TEXT NOT NULL,
    order_num INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- FAQs table
CREATE TABLE faqs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(255) NOT NULL,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    order_num INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Privacy sections table
CREATE TABLE privacy_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    content TEXT NOT NULL,
    list_items TEXT[],
    order_num INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Contact info table
CREATE TABLE contact_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    value TEXT NOT NULL,
    order_num INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Categories table
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Products table
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    description TEXT,
    image_url TEXT,
    category VARCHAR(100) NOT NULL,
    featured BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample categories
INSERT INTO categories (name, slug, description) VALUES
('Sarees', 'sarees', 'Traditional Indian sarees in various styles and fabrics'),
('Lehengas', 'lehengas', 'Designer lehengas for special occasions'),
('Kurtis', 'kurtis', 'Contemporary and traditional kurtis');

-- Insert sample products
INSERT INTO products (name, price, description, category_id, featured) VALUES
('Traditional Silk Saree', 5999.00, 'Handwoven silk saree with traditional design',
  (SELECT id FROM categories WHERE slug = 'sarees'), true),
('Designer Lehenga', 12999.00, 'Embroidered designer lehenga with contemporary patterns',
  (SELECT id FROM categories WHERE slug = 'lehengas'), true),
('Casual Cotton Kurti', 1499.00, 'Comfortable cotton kurti for daily wear',
  (SELECT id FROM categories WHERE slug = 'kurtis'), true),
('Party Wear Lehenga', 3999.00, 'Elegant party wear lehenga with modern design',
  (SELECT id FROM categories WHERE slug = 'lehengas'), true);

-- Create product_images table
CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    alt_text TEXT,
    is_primary BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample product images
INSERT INTO product_images (product_id, image_url, alt_text, is_primary) VALUES
((SELECT id FROM products WHERE name = 'Traditional Silk Saree'),
 'https://example.com/images/saree1.jpg', 'Traditional Silk Saree Front View', true),
((SELECT id FROM products WHERE name = 'Designer Lehenga'),
 'https://example.com/images/lehenga1.jpg', 'Designer Lehenga Front View', true),
((SELECT id FROM products WHERE name = 'Casual Cotton Kurti'),
 'https://example.com/images/kurti1.jpg', 'Casual Cotton Kurti Front View', true),
((SELECT id FROM products WHERE name = 'Party Wear Lehenga'),
 'https://example.com/images/lehenga2.jpg', 'Party Wear Lehenga Front View', true);

-- Insert About page content
INSERT INTO about_sections (title, content, order_num) VALUES
('', 'Welcome to Nirchal, your premier destination for exquisite Indian ethnic wear. We are passionate about bringing the rich heritage of Indian craftsmanship to the modern fashion landscape.', 1),
('Our Story', 'Founded in 2020, Nirchal began with a vision to make authentic Indian ethnic wear accessible to fashion enthusiasts worldwide. We work directly with artisans and designers across India to bring you carefully curated collections that blend traditional techniques with contemporary designs.', 2),
('Our Mission', 'We strive to preserve and promote India''s rich textile heritage while making it relevant for the modern customer. Every piece in our collection is thoughtfully designed to ensure both authenticity and wearability.', 3),
('Quality & Craftsmanship', 'Quality is at the heart of everything we do. Each garment is crafted with attention to detail, using premium fabrics and traditional techniques. We maintain strict quality control measures to ensure that every piece meets our high standards.', 4);

-- Insert FAQ content
INSERT INTO faqs (category, question, answer, order_num) VALUES
('Orders & Shipping', 'How can I track my order?', 'Once your order is shipped, you''ll receive a tracking number via email and SMS. You can use this number to track your order through our website or the courier partner''s tracking portal.', 1),
('Orders & Shipping', 'What are the shipping charges?', 'We offer free standard shipping on orders above ₹2999. For orders below this amount, a flat shipping fee of ₹99 applies. Express delivery is available at an additional cost of ₹199.', 2),
('Returns & Refunds', 'What is your return policy?', 'We accept returns within 30 days of delivery. Items must be unworn, unused, and in their original packaging with all tags attached. Some items like intimate wear and customized products are not eligible for return.', 3),
('Returns & Refunds', 'How long does it take to process a refund?', 'Once we receive your return, refunds are processed within 5-7 business days. The amount will be credited to your original payment method.', 4),
('Product & Sizing', 'How do I find my correct size?', 'You can refer to our detailed size guide available on each product page. We also have a comprehensive size guide section that provides measurements for all our categories.', 5),
('Product & Sizing', 'Can I customize my order?', 'Yes, we offer customization options for select products. Look for the ''Customize'' option on the product page. Please note that customized items are not eligible for return or exchange.', 6),
('Account & Payment', 'What payment methods do you accept?', 'We accept all major credit/debit cards, UPI, net banking, and popular digital wallets. We also offer Cash on Delivery (COD) for select locations.', 7),
('Account & Payment', 'How do I reset my password?', 'Click on ''Forgot Password'' on the login page. Enter your registered email address, and we''ll send you a link to reset your password.', 8);

-- Insert Privacy Policy content
INSERT INTO privacy_sections (title, content, list_items, order_num) VALUES
('', 'At Nirchal, we take your privacy seriously. This policy outlines how we collect, use, and protect your personal information.', NULL, 1),
('Information We Collect', '', ARRAY[
    'Personal information (name, email, shipping address)',
    'Payment information (processed securely through our payment partners)',
    'Shopping preferences and history',
    'Device and browser information'
], 2),
('How We Use Your Information', '', ARRAY[
    'Process and fulfill your orders',
    'Communicate about your purchases',
    'Send promotional offers (with your consent)',
    'Improve our website and services',
    'Prevent fraud and enhance security'
], 3),
('Information Sharing', 'We never sell your personal information to third parties. We only share your information with:', ARRAY[
    'Shipping partners to deliver your orders',
    'Payment processors to handle transactions',
    'Service providers who assist our operations'
], 4),
('Data Security', 'We implement appropriate technical and organizational measures to protect your personal information. However, no method of transmission over the internet is 100% secure, and we cannot guarantee absolute security.', NULL, 5),
('Your Rights', 'You have the right to:', ARRAY[
    'Access your personal information',
    'Correct inaccurate information',
    'Request deletion of your information',
    'Opt-out of marketing communications'
], 6);

-- Insert Contact Information
INSERT INTO contact_info (type, value, order_num) VALUES
('support_email', 'support@nirchal.com', 1),
('privacy_email', 'privacy@nirchal.com', 2),
('phone', '+91 123 456 7890 (10 AM - 7 PM IST)', 3);