-- Privacy Policy Sections
DELETE FROM privacy_sections WHERE id IS NOT NULL;
INSERT INTO privacy_sections (title, content, list_items, order_num) VALUES
('Introduction', 'At Nirchal, we take your privacy seriously. This policy outlines how we collect, use, and protect your personal information.', NULL, 1),
('Information We Collect', 'We collect various types of information to provide and improve our services.', ARRAY[
    'Personal information (name, email, shipping address)',
    'Payment information (processed securely)',
    'Shopping preferences and history',
    'Device and browser information'
], 2),
('How We Use Your Information', 'Your information helps us provide and improve our services.', ARRAY[
    'Process and fulfill your orders',
    'Send order updates and shipping notifications',
    'Improve our website and services',
    'Provide customer support'
], 3),
('Data Security', 'We implement industry-standard security measures to protect your data. All payment information is encrypted and processed securely through our payment partners.', NULL, 4),
('Your Rights', 'You have control over your personal data.', ARRAY[
    'Access your personal information',
    'Request data deletion',
    'Opt-out of marketing communications',
    'Update your preferences'
], 5);

-- About Sections
DELETE FROM about_sections WHERE id IS NOT NULL;
INSERT INTO about_sections (title, content, order_num) VALUES
('Our Story', 'Founded in 2020, Nirchal began with a vision to make authentic Indian ethnic wear accessible to fashion enthusiasts worldwide. We work directly with artisans and designers across India to bring you carefully curated collections that blend traditional techniques with contemporary designs.', 1),
('Our Mission', 'We strive to preserve and promote India''s rich textile heritage while making it relevant for the modern customer. Every piece in our collection is thoughtfully designed to ensure both authenticity and wearability.', 2),
('Quality & Craftsmanship', 'Quality is at the heart of everything we do. Each garment is crafted with meticulous attention to detail, using premium fabrics and traditional techniques. We maintain strict quality control measures to ensure that every piece meets our high standards.', 3),
('Sustainability', 'We are committed to sustainable fashion. Our partnerships with local artisans not only preserve traditional craftsmanship but also support local communities. We use eco-friendly packaging and encourage sustainable shopping practices.', 4),
('Our Team', 'Our team consists of passionate individuals who share a love for Indian fashion and craftsmanship. From our designers to our customer service representatives, everyone is committed to providing you with the best shopping experience.', 5);

-- Contact Info
DELETE FROM contact_info WHERE id IS NOT NULL;
INSERT INTO contact_info (type, value, order_num) VALUES
('business_hours', 'Monday to Saturday: 10 AM - 7 PM IST', 1),
('phone', '+91 123 456 7890', 2),
('email', 'support@nirchal.com', 3),
('address', '123 Fashion Street, Mumbai, Maharashtra 400001, India', 4),
('customer_service', 'For the fastest response, please email us or use our contact form below.', 5);

-- Create Shipping Info table if it doesn't exist
CREATE TABLE IF NOT EXISTS shipping_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    order_num INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Populate Shipping Info
DELETE FROM shipping_info WHERE id IS NOT NULL;
INSERT INTO shipping_info (title, content, order_num) VALUES
('Delivery Areas', 'We currently deliver to all major cities in India. International shipping is available to select countries.', 1),
('Standard Shipping', 'Free shipping on orders above ₹2999. For orders below this amount, a flat fee of ₹99 applies. Delivery typically takes 5-7 business days.', 2),
('Express Shipping', 'Available at an additional cost of ₹199. Guaranteed delivery within 2-3 business days for most locations.', 3),
('Tracking Orders', 'Once your order is shipped, you will receive a tracking number via email and SMS. You can track your order through our website or the courier partner''s portal.', 4),
('International Shipping', 'International shipping costs and delivery times vary by location. Customs duties and taxes may apply.', 5);

-- Create Return Policy table if it doesn't exist
CREATE TABLE IF NOT EXISTS return_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    order_num INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Populate Return Policy
DELETE FROM return_policy WHERE id IS NOT NULL;
INSERT INTO return_policy (title, content, order_num) VALUES
('Return Window', 'We accept returns within 30 days of delivery. Items must be unworn, unused, and in their original packaging with all tags attached.', 1),
('Non-Returnable Items', 'For hygiene reasons, certain items like jewelry, intimate wear, and customized products are not eligible for return.', 2),
('Return Process', 'To initiate a return, log into your account and select the order you wish to return. Print the return label and drop off the package at your nearest courier partner location.', 3),
('Refund Timeline', 'Once we receive and inspect your return, refunds are processed within 5-7 business days. The amount will be credited to your original payment method.', 4),
('Exchange Policy', 'We offer free exchanges within the return window. Simply initiate an exchange request through your account, and we''ll help you select a different size or color.', 5);

-- Create Terms table if it doesn't exist
CREATE TABLE IF NOT EXISTS terms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    order_num INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Populate Terms
DELETE FROM terms WHERE id IS NOT NULL;
INSERT INTO terms (title, content, order_num) VALUES
('Acceptance of Terms', 'By accessing and using Nirchal''s website and services, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.', 1),
('User Accounts', 'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must immediately notify us of any unauthorized use.', 2),
('Product Information', 'We strive to display accurate product information, including prices and availability. However, we reserve the right to correct any errors and modify prices without prior notice.', 3),
('Order Acceptance', 'Your order is an offer to buy our product. We reserve the right to accept or decline your order for any reason, including product availability or errors in pricing.', 4),
('Intellectual Property', 'All content on our website, including text, graphics, logos, and images, is our property and protected by copyright laws. You may not use our content without our express permission.', 5);

-- Enable RLS on all tables
ALTER TABLE privacy_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE about_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipping_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE return_policy ENABLE ROW LEVEL SECURITY;
ALTER TABLE terms ENABLE ROW LEVEL SECURITY;

-- Create public read access policies for all tables
CREATE POLICY "Enable public read access to privacy_sections" ON privacy_sections FOR SELECT USING (true);
CREATE POLICY "Enable public read access to about_sections" ON about_sections FOR SELECT USING (true);
CREATE POLICY "Enable public read access to contact_info" ON contact_info FOR SELECT USING (true);
CREATE POLICY "Enable public read access to shipping_info" ON shipping_info FOR SELECT USING (true);
CREATE POLICY "Enable public read access to return_policy" ON return_policy FOR SELECT USING (true);
CREATE POLICY "Enable public read access to terms" ON terms FOR SELECT USING (true);

-- Verify data
SELECT 'Privacy Sections' as table_name, COUNT(*) as count FROM privacy_sections
UNION ALL
SELECT 'About Sections', COUNT(*) FROM about_sections
UNION ALL
SELECT 'Contact Info', COUNT(*) FROM contact_info
UNION ALL
SELECT 'Shipping Info', COUNT(*) FROM shipping_info
UNION ALL
SELECT 'Return Policy', COUNT(*) FROM return_policy
UNION ALL
SELECT 'Terms', COUNT(*) FROM terms;
