-- Allow all users (including anon) to select reviews
CREATE POLICY "Allow public read of product reviews"
  ON product_reviews
  FOR SELECT
  USING (true);
-- Product Reviews table
CREATE TABLE product_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id),
    user_name VARCHAR(255),
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    helpful INTEGER DEFAULT 0,
    images TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- RLS for product_reviews
drop policy if exists "Authenticated can select product_reviews" on product_reviews;
create policy "Authenticated can select product_reviews" on product_reviews
  for select using (true);

drop policy if exists "Authenticated can insert product_reviews" on product_reviews;
create policy "Authenticated can insert product_reviews" on product_reviews
  for insert to authenticated with check (auth.role() = 'authenticated');

alter table product_reviews enable row level security;
