-- Product Reviews table (idempotent)
CREATE TABLE IF NOT EXISTS product_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id),
    user_name VARCHAR(255),
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    helpful INTEGER DEFAULT 0,
    images TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- RLS for product_reviews
alter table product_reviews enable row level security;

-- Public read policy (idempotent)
drop policy if exists "Allow public read of product reviews" on product_reviews;
create policy "Allow public read of product reviews" on product_reviews
  for select using (true);

-- Authenticated can read (kept for compatibility; same as public read)
drop policy if exists "Authenticated can select product_reviews" on product_reviews;
create policy "Authenticated can select product_reviews" on product_reviews
  for select using (true);

drop policy if exists "Authenticated can insert product_reviews" on product_reviews;
create policy "Authenticated can insert product_reviews" on product_reviews
  for insert to authenticated with check (auth.role() = 'authenticated');

-- OPTIONAL: In development, you may temporarily allow anonymous inserts for testing.
-- DO NOT enable this in production.
-- drop policy if exists "Anon can insert product_reviews (DEV ONLY)" on product_reviews;
-- create policy "Anon can insert product_reviews (DEV ONLY)" on product_reviews
--   for insert to anon with check (true);
