-- Safe Orders and Analytics Schema for Nirchal Admin Dashboard
-- This file creates tables only if they don't already exist

-- Customers table
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20),
    date_of_birth DATE,
    gender VARCHAR(10),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Customer addresses table
CREATE TABLE IF NOT EXISTS customer_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
    type VARCHAR(20) DEFAULT 'billing', -- 'billing', 'shipping'
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    company VARCHAR(100),
    address_line_1 VARCHAR(255) NOT NULL,
    address_line_2 VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(100) DEFAULT 'India',
    is_default BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Orders table
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(50) NOT NULL UNIQUE,
    customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
    status VARCHAR(50) DEFAULT 'pending', -- 'pending', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded'
    payment_status VARCHAR(50) DEFAULT 'pending', -- 'pending', 'paid', 'failed', 'refunded'
    payment_method VARCHAR(50), -- 'razorpay', 'stripe', 'cod', 'bank_transfer'
    payment_transaction_id VARCHAR(255),
    
    -- Pricing
    subtotal DECIMAL(10,2) NOT NULL DEFAULT 0,
    tax_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    shipping_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    total_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    
    -- Billing address
    billing_first_name VARCHAR(100) NOT NULL,
    billing_last_name VARCHAR(100) NOT NULL,
    billing_company VARCHAR(100),
    billing_address_line_1 VARCHAR(255) NOT NULL,
    billing_address_line_2 VARCHAR(255),
    billing_city VARCHAR(100) NOT NULL,
    billing_state VARCHAR(100) NOT NULL,
    billing_postal_code VARCHAR(20) NOT NULL,
    billing_country VARCHAR(100) DEFAULT 'India',
    billing_phone VARCHAR(20),
    billing_email VARCHAR(255) NOT NULL,
    
    -- Shipping address
    shipping_first_name VARCHAR(100) NOT NULL,
    shipping_last_name VARCHAR(100) NOT NULL,
    shipping_company VARCHAR(100),
    shipping_address_line_1 VARCHAR(255) NOT NULL,
    shipping_address_line_2 VARCHAR(255),
    shipping_city VARCHAR(100) NOT NULL,
    shipping_state VARCHAR(100) NOT NULL,
    shipping_postal_code VARCHAR(20) NOT NULL,
    shipping_country VARCHAR(100) DEFAULT 'India',
    shipping_phone VARCHAR(20),
    
    -- Timestamps
    shipped_at TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- Notes
    notes TEXT,
    admin_notes TEXT
);

-- Order items table
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    product_variant_id BIGINT REFERENCES product_variants(id) ON DELETE SET NULL,
    
    -- Product details at time of order (for historical accuracy)
    product_name VARCHAR(255) NOT NULL,
    product_sku VARCHAR(100),
    variant_size VARCHAR(50),
    variant_color VARCHAR(50),
    variant_material VARCHAR(100),
    
    -- Pricing
    unit_price DECIMAL(10,2) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    total_price DECIMAL(10,2) NOT NULL,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Order status history table
CREATE TABLE IF NOT EXISTS order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL,
    comment TEXT,
    notify_customer BOOLEAN DEFAULT false,
    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Product analytics/stats table
CREATE TABLE IF NOT EXISTS product_analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    views INTEGER DEFAULT 0,
    orders INTEGER DEFAULT 0,
    quantity_sold INTEGER DEFAULT 0,
    revenue DECIMAL(10,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add unique constraint only if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'product_analytics_product_id_date_key'
    ) THEN
        ALTER TABLE product_analytics ADD CONSTRAINT product_analytics_product_id_date_key UNIQUE(product_id, date);
    END IF;
END $$;

-- Daily analytics summary table
CREATE TABLE IF NOT EXISTS daily_analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    total_orders INTEGER DEFAULT 0,
    total_customers INTEGER DEFAULT 0,
    new_customers INTEGER DEFAULT 0,
    total_revenue DECIMAL(10,2) DEFAULT 0,
    total_products_sold INTEGER DEFAULT 0,
    average_order_value DECIMAL(10,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes only if they don't exist
DO $$
BEGIN
    -- Orders indexes
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_orders_customer_id') THEN
        CREATE INDEX idx_orders_customer_id ON orders(customer_id);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_orders_status') THEN
        CREATE INDEX idx_orders_status ON orders(status);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_orders_created_at') THEN
        CREATE INDEX idx_orders_created_at ON orders(created_at);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_orders_order_number') THEN
        CREATE INDEX idx_orders_order_number ON orders(order_number);
    END IF;

    -- Order items indexes
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_order_items_order_id') THEN
        CREATE INDEX idx_order_items_order_id ON order_items(order_id);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_order_items_product_id') THEN
        CREATE INDEX idx_order_items_product_id ON order_items(product_id);
    END IF;

    -- Product analytics indexes
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_product_analytics_product_id') THEN
        CREATE INDEX idx_product_analytics_product_id ON product_analytics(product_id);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_product_analytics_date') THEN
        CREATE INDEX idx_product_analytics_date ON product_analytics(date);
    END IF;

    -- Daily analytics indexes
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_daily_analytics_date') THEN
        CREATE INDEX idx_daily_analytics_date ON daily_analytics(date);
    END IF;

    -- Inventory history indexes (if table exists)
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'inventory_history') THEN
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_inventory_history_variant_id') THEN
            CREATE INDEX idx_inventory_history_variant_id ON inventory_history(product_variant_id);
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_inventory_history_created_at') THEN
            CREATE INDEX idx_inventory_history_created_at ON inventory_history(created_at);
        END IF;
    END IF;
END $$;

-- Insert sample customers (only if table is empty)
INSERT INTO customers (first_name, last_name, email, phone) 
SELECT 'Priya', 'Sharma', 'priya.sharma@email.com', '+91 98765 43210'
WHERE NOT EXISTS (SELECT 1 FROM customers WHERE email = 'priya.sharma@email.com');

INSERT INTO customers (first_name, last_name, email, phone) 
SELECT 'Arjun', 'Patel', 'arjun.patel@email.com', '+91 98765 43211'
WHERE NOT EXISTS (SELECT 1 FROM customers WHERE email = 'arjun.patel@email.com');

INSERT INTO customers (first_name, last_name, email, phone) 
SELECT 'Meera', 'Singh', 'meera.singh@email.com', '+91 98765 43212'
WHERE NOT EXISTS (SELECT 1 FROM customers WHERE email = 'meera.singh@email.com');

INSERT INTO customers (first_name, last_name, email, phone) 
SELECT 'Rohit', 'Kumar', 'rohit.kumar@email.com', '+91 98765 43213'
WHERE NOT EXISTS (SELECT 1 FROM customers WHERE email = 'rohit.kumar@email.com');

INSERT INTO customers (first_name, last_name, email, phone) 
SELECT 'Anita', 'Gupta', 'anita.gupta@email.com', '+91 98765 43214'
WHERE NOT EXISTS (SELECT 1 FROM customers WHERE email = 'anita.gupta@email.com');

INSERT INTO customers (first_name, last_name, email, phone) 
SELECT 'Vikram', 'Joshi', 'vikram.joshi@email.com', '+91 98765 43215'
WHERE NOT EXISTS (SELECT 1 FROM customers WHERE email = 'vikram.joshi@email.com');

-- Insert sample orders (only if not already present)
INSERT INTO orders (order_number, customer_id, status, payment_status, payment_method, 
    subtotal, tax_amount, shipping_amount, total_amount,
    billing_first_name, billing_last_name, billing_address_line_1, billing_city, billing_state, billing_postal_code, billing_email,
    shipping_first_name, shipping_last_name, shipping_address_line_1, shipping_city, shipping_state, shipping_postal_code,
    created_at) 
SELECT 'ORD-001', 1, 'processing', 'paid', 'razorpay', 2124.15, 374.85, 0, 2499.00,
    'Priya', 'Sharma', '123 MG Road', 'Mumbai', 'Maharashtra', '400001', 'priya.sharma@email.com',
    'Priya', 'Sharma', '123 MG Road', 'Mumbai', 'Maharashtra', '400001',
    NOW() - INTERVAL '2 minutes'
WHERE NOT EXISTS (SELECT 1 FROM orders WHERE order_number = 'ORD-001');

INSERT INTO orders (order_number, customer_id, status, payment_status, payment_method, 
    subtotal, tax_amount, shipping_amount, total_amount,
    billing_first_name, billing_last_name, billing_address_line_1, billing_city, billing_state, billing_postal_code, billing_email,
    shipping_first_name, shipping_last_name, shipping_address_line_1, shipping_city, shipping_state, shipping_postal_code,
    created_at) 
SELECT 'ORD-002', 2, 'shipped', 'paid', 'stripe', 3644.07, 654.93, 0, 4299.00,
    'Arjun', 'Patel', '456 Park Street', 'Kolkata', 'West Bengal', '700016', 'arjun.patel@email.com',
    'Arjun', 'Patel', '456 Park Street', 'Kolkata', 'West Bengal', '700016',
    NOW() - INTERVAL '15 minutes'
WHERE NOT EXISTS (SELECT 1 FROM orders WHERE order_number = 'ORD-002');

INSERT INTO orders (order_number, customer_id, status, payment_status, payment_method, 
    subtotal, tax_amount, shipping_amount, total_amount,
    billing_first_name, billing_last_name, billing_address_line_1, billing_city, billing_state, billing_postal_code, billing_email,
    shipping_first_name, shipping_last_name, shipping_address_line_1, shipping_city, shipping_state, shipping_postal_code,
    created_at) 
SELECT 'ORD-003', 3, 'delivered', 'paid', 'cod', 1610.17, 288.83, 0, 1899.00,
    'Meera', 'Singh', '789 Brigade Road', 'Bangalore', 'Karnataka', '560001', 'meera.singh@email.com',
    'Meera', 'Singh', '789 Brigade Road', 'Bangalore', 'Karnataka', '560001',
    NOW() - INTERVAL '1 hour'
WHERE NOT EXISTS (SELECT 1 FROM orders WHERE order_number = 'ORD-003');

INSERT INTO orders (order_number, customer_id, status, payment_status, payment_method, 
    subtotal, tax_amount, shipping_amount, total_amount,
    billing_first_name, billing_last_name, billing_address_line_1, billing_city, billing_state, billing_postal_code, billing_email,
    shipping_first_name, shipping_last_name, shipping_address_line_1, shipping_city, shipping_state, shipping_postal_code,
    created_at) 
SELECT 'ORD-004', 4, 'processing', 'paid', 'razorpay', 3050.85, 548.15, 0, 3599.00,
    'Rohit', 'Kumar', '321 CP', 'New Delhi', 'Delhi', '110001', 'rohit.kumar@email.com',
    'Rohit', 'Kumar', '321 CP', 'New Delhi', 'Delhi', '110001',
    NOW() - INTERVAL '2 hours'
WHERE NOT EXISTS (SELECT 1 FROM orders WHERE order_number = 'ORD-004');

INSERT INTO orders (order_number, customer_id, status, payment_status, payment_method, 
    subtotal, tax_amount, shipping_amount, total_amount,
    billing_first_name, billing_last_name, billing_address_line_1, billing_city, billing_state, billing_postal_code, billing_email,
    shipping_first_name, shipping_last_name, shipping_address_line_1, shipping_city, shipping_state, shipping_postal_code,
    created_at) 
SELECT 'ORD-005', 5, 'delivered', 'paid', 'razorpay', 4237.29, 761.71, 0, 4999.00,
    'Anita', 'Gupta', '654 FC Road', 'Pune', 'Maharashtra', '411005', 'anita.gupta@email.com',
    'Anita', 'Gupta', '654 FC Road', 'Pune', 'Maharashtra', '411005',
    NOW() - INTERVAL '1 day'
WHERE NOT EXISTS (SELECT 1 FROM orders WHERE order_number = 'ORD-005');

INSERT INTO orders (order_number, customer_id, status, payment_status, payment_method, 
    subtotal, tax_amount, shipping_amount, total_amount,
    billing_first_name, billing_last_name, billing_address_line_1, billing_city, billing_state, billing_postal_code, billing_email,
    shipping_first_name, shipping_last_name, shipping_address_line_1, shipping_city, shipping_state, shipping_postal_code,
    created_at) 
SELECT 'ORD-006', 6, 'shipped', 'paid', 'stripe', 6779.66, 1219.34, 0, 7999.00,
    'Vikram', 'Joshi', '987 Mall Road', 'Shimla', 'Himachal Pradesh', '171001', 'vikram.joshi@email.com',
    'Vikram', 'Joshi', '987 Mall Road', 'Shimla', 'Himachal Pradesh', '171001',
    NOW() - INTERVAL '2 days'
WHERE NOT EXISTS (SELECT 1 FROM orders WHERE order_number = 'ORD-006');

-- Insert sample order items (using existing product IDs from the database)
DO $$
DECLARE
    order_1_id INTEGER;
    order_2_id INTEGER;
    order_3_id INTEGER;
    order_4_id INTEGER;
    order_5_id INTEGER;
    order_6_id INTEGER;
    product_1_id INTEGER;
    product_2_id INTEGER;
    product_3_id INTEGER;
BEGIN
    -- Get order IDs
    SELECT id INTO order_1_id FROM orders WHERE order_number = 'ORD-001';
    SELECT id INTO order_2_id FROM orders WHERE order_number = 'ORD-002';
    SELECT id INTO order_3_id FROM orders WHERE order_number = 'ORD-003';
    SELECT id INTO order_4_id FROM orders WHERE order_number = 'ORD-004';
    SELECT id INTO order_5_id FROM orders WHERE order_number = 'ORD-005';
    SELECT id INTO order_6_id FROM orders WHERE order_number = 'ORD-006';
    
    -- Get product IDs (use existing products)
    SELECT id INTO product_1_id FROM products ORDER BY id LIMIT 1;
    SELECT id INTO product_2_id FROM products ORDER BY id LIMIT 1 OFFSET 1;
    SELECT id INTO product_3_id FROM products ORDER BY id LIMIT 1 OFFSET 2;
    
    -- Insert order items if they don't exist
    IF order_1_id IS NOT NULL AND product_1_id IS NOT NULL THEN
        INSERT INTO order_items (order_id, product_id, product_name, product_sku, unit_price, quantity, total_price) 
        SELECT order_1_id, product_1_id, 'Traditional Silk Saree', 'TSS-001', 2499.00, 1, 2499.00
        WHERE NOT EXISTS (SELECT 1 FROM order_items WHERE order_id = order_1_id);
    END IF;
    
    IF order_2_id IS NOT NULL AND product_2_id IS NOT NULL THEN
        INSERT INTO order_items (order_id, product_id, product_name, product_sku, unit_price, quantity, total_price) 
        SELECT order_2_id, product_2_id, 'Designer Lehenga', 'DL-001', 4299.00, 1, 4299.00
        WHERE NOT EXISTS (SELECT 1 FROM order_items WHERE order_id = order_2_id);
    END IF;
    
    IF order_3_id IS NOT NULL AND product_3_id IS NOT NULL THEN
        INSERT INTO order_items (order_id, product_id, product_name, product_sku, unit_price, quantity, total_price) 
        SELECT order_3_id, product_3_id, 'Casual Cotton Kurti', 'CCK-001', 1899.00, 1, 1899.00
        WHERE NOT EXISTS (SELECT 1 FROM order_items WHERE order_id = order_3_id);
    END IF;
    
    IF order_4_id IS NOT NULL AND product_2_id IS NOT NULL THEN
        INSERT INTO order_items (order_id, product_id, product_name, product_sku, unit_price, quantity, total_price) 
        SELECT order_4_id, product_2_id, 'Designer Lehenga', 'DL-001', 3599.00, 1, 3599.00
        WHERE NOT EXISTS (SELECT 1 FROM order_items WHERE order_id = order_4_id);
    END IF;
    
    IF order_5_id IS NOT NULL AND product_1_id IS NOT NULL THEN
        INSERT INTO order_items (order_id, product_id, product_name, product_sku, unit_price, quantity, total_price) 
        SELECT order_5_id, product_1_id, 'Traditional Silk Saree', 'TSS-001', 4999.00, 1, 4999.00
        WHERE NOT EXISTS (SELECT 1 FROM order_items WHERE order_id = order_5_id);
    END IF;
    
    IF order_6_id IS NOT NULL AND product_2_id IS NOT NULL THEN
        INSERT INTO order_items (order_id, product_id, product_name, product_sku, unit_price, quantity, total_price) 
        SELECT order_6_id, product_2_id, 'Designer Lehenga', 'DL-002', 7999.00, 1, 7999.00
        WHERE NOT EXISTS (SELECT 1 FROM order_items WHERE order_id = order_6_id);
    END IF;
END $$;

-- Create functions to automatically update analytics
CREATE OR REPLACE FUNCTION update_product_analytics()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO product_analytics (product_id, date, orders, quantity_sold, revenue)
    VALUES (NEW.product_id, CURRENT_DATE, 1, NEW.quantity, NEW.total_price)
    ON CONFLICT (product_id, date)
    DO UPDATE SET
        orders = product_analytics.orders + 1,
        quantity_sold = product_analytics.quantity_sold + NEW.quantity,
        revenue = product_analytics.revenue + NEW.total_price,
        updated_at = CURRENT_TIMESTAMP;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_daily_analytics()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO daily_analytics (date, total_orders, total_revenue, total_products_sold, average_order_value)
    VALUES (CURRENT_DATE, 1, NEW.total_amount, 
        (SELECT COALESCE(SUM(quantity), 0) FROM order_items WHERE order_id = NEW.id),
        NEW.total_amount)
    ON CONFLICT (date)
    DO UPDATE SET
        total_orders = daily_analytics.total_orders + 1,
        total_revenue = daily_analytics.total_revenue + NEW.total_amount,
        total_products_sold = daily_analytics.total_products_sold + 
            (SELECT COALESCE(SUM(quantity), 0) FROM order_items WHERE order_id = NEW.id),
        average_order_value = (daily_analytics.total_revenue + NEW.total_amount) / (daily_analytics.total_orders + 1),
        updated_at = CURRENT_TIMESTAMP;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create triggers only if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trigger_update_product_analytics') THEN
        CREATE TRIGGER trigger_update_product_analytics
            AFTER INSERT ON order_items
            FOR EACH ROW
            EXECUTE FUNCTION update_product_analytics();
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trigger_update_daily_analytics') THEN
        CREATE TRIGGER trigger_update_daily_analytics
            AFTER INSERT ON orders
            FOR EACH ROW
            EXECUTE FUNCTION update_daily_analytics();
    END IF;
END $$;

-- Create views (drop and recreate to ensure they're up to date)
DROP VIEW IF EXISTS recent_orders_view;
CREATE VIEW recent_orders_view AS
SELECT 
    o.id,
    o.order_number,
    o.status,
    o.payment_status,
    o.total_amount,
    o.created_at,
    c.first_name,
    c.last_name,
    c.email,
    CONCAT(c.first_name, ' ', c.last_name) as customer_name,
    CONCAT(UPPER(LEFT(c.first_name, 1)), UPPER(LEFT(c.last_name, 1))) as avatar_initials,
    CASE 
        WHEN o.created_at > NOW() - INTERVAL '5 minutes' THEN EXTRACT(EPOCH FROM (NOW() - o.created_at))/60 || ' mins ago'
        WHEN o.created_at > NOW() - INTERVAL '1 hour' THEN EXTRACT(EPOCH FROM (NOW() - o.created_at))/60 || ' mins ago'
        WHEN o.created_at > NOW() - INTERVAL '1 day' THEN EXTRACT(EPOCH FROM (NOW() - o.created_at))/3600 || ' hours ago'
        ELSE EXTRACT(EPOCH FROM (NOW() - o.created_at))/86400 || ' days ago'
    END as time_ago
FROM orders o
LEFT JOIN customers c ON o.customer_id = c.id
ORDER BY o.created_at DESC;

DROP VIEW IF EXISTS top_products_view;
CREATE VIEW top_products_view AS
SELECT 
    p.id,
    p.name,
    COALESCE(SUM(pa.quantity_sold), 0) as total_sales,
    COALESCE(SUM(pa.revenue), 0) as total_revenue,
    CASE 
        WHEN LAG(SUM(pa.quantity_sold)) OVER (PARTITION BY p.id ORDER BY EXTRACT(DOW FROM pa.date)) IS NULL THEN '+0%'
        ELSE CONCAT('+', ROUND((SUM(pa.quantity_sold) - LAG(SUM(pa.quantity_sold)) OVER (PARTITION BY p.id ORDER BY EXTRACT(DOW FROM pa.date))) * 100.0 / NULLIF(LAG(SUM(pa.quantity_sold)) OVER (PARTITION BY p.id ORDER BY EXTRACT(DOW FROM pa.date)), 0), 0), '%')
    END as trend,
    pi.image_url
FROM products p
LEFT JOIN product_analytics pa ON p.id = pa.product_id AND pa.date >= CURRENT_DATE - INTERVAL '7 days'
LEFT JOIN product_images pi ON p.id = pi.product_id AND pi.is_primary = true
GROUP BY p.id, p.name, pi.image_url
HAVING COALESCE(SUM(pa.quantity_sold), 0) > 0
ORDER BY total_sales DESC
LIMIT 10;
