-- Migration: Fix customer_addresses id column to auto-increment
-- Description: Add GENERATED BY DEFAULT AS IDENTITY to id column
-- Date: 2025-01-24
-- IMPORTANT: Run this migration FIRST before the RPC functions migration

-- Step 1: Check current max id and prepare
DO $$
DECLARE
  max_id bigint;
BEGIN
  -- Get the maximum current id (will be 0 if table is empty)
  SELECT COALESCE(MAX(id), 0) INTO max_id FROM public.customer_addresses;
  RAISE NOTICE 'Current max id in customer_addresses: %', max_id;
END $$;

-- Step 2: Add IDENTITY to the id column (if not already exists)
-- This will create the sequence automatically
DO $$
BEGIN
  -- Check if column already has IDENTITY
  IF NOT EXISTS (
    SELECT 1 
    FROM pg_attribute a
    JOIN pg_class c ON a.attrelid = c.oid
    JOIN pg_namespace n ON c.relnamespace = n.oid
    WHERE n.nspname = 'public'
      AND c.relname = 'customer_addresses'
      AND a.attname = 'id'
      AND a.attidentity IN ('a', 'd')  -- 'a' = ALWAYS, 'd' = BY DEFAULT
  ) THEN
    -- Add IDENTITY only if it doesn't exist
    ALTER TABLE public.customer_addresses 
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
      );
    RAISE NOTICE 'Added IDENTITY to customer_addresses.id column';
  ELSE
    RAISE NOTICE 'Column customer_addresses.id already has IDENTITY, skipping';
  END IF;
END $$;

-- Step 3: Set the sequence to the correct starting value
DO $$
DECLARE
  max_id bigint;
  seq_name text;
BEGIN
  -- Get the maximum current id
  SELECT COALESCE(MAX(id), 0) INTO max_id FROM public.customer_addresses;
  
  -- Get the sequence name (PostgreSQL auto-creates it with IDENTITY)
  SELECT pg_get_serial_sequence('public.customer_addresses', 'id') INTO seq_name;
  
  -- Set sequence to continue from max_id + 1
  IF max_id > 0 THEN
    PERFORM setval(seq_name, max_id);
    RAISE NOTICE 'Set sequence % to start from %', seq_name, max_id + 1;
  ELSE
    RAISE NOTICE 'Table is empty, sequence will start from 1';
  END IF;
END $$;

-- Step 4: Grant permissions on the sequence
DO $$
DECLARE
  seq_name text;
BEGIN
  -- Get the sequence name
  SELECT pg_get_serial_sequence('public.customer_addresses', 'id') INTO seq_name;
  
  -- Grant usage to necessary roles
  EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO anon, authenticated, postgres', seq_name);
  
  RAISE NOTICE 'Granted permissions on sequence %', seq_name;
END $$;

-- Verify the setup
DO $$
DECLARE
  has_identity boolean;
  seq_name text;
BEGIN
  -- Check if IDENTITY was added
  SELECT attidentity != '' INTO has_identity
  FROM pg_attribute 
  WHERE attrelid = 'public.customer_addresses'::regclass 
    AND attname = 'id';
  
  IF has_identity THEN
    SELECT pg_get_serial_sequence('public.customer_addresses', 'id') INTO seq_name;
    RAISE NOTICE '✅ SUCCESS: customer_addresses.id now has IDENTITY with sequence: %', seq_name;
  ELSE
    RAISE EXCEPTION '❌ FAILED: Could not add IDENTITY to customer_addresses.id';
  END IF;
END $$;
