name: Lint (non-blocking)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Run ESLint (do not fail)
        run: |
          npm run lint || echo "ESLint warnings/errors detected (non-blocking)"

      - name: Type check (do not fail)
        run: |
          npx tsc -p tsconfig.json --noEmit || echo "TypeScript issues detected (non-blocking)"
